# for MacOS
if [[ /Users/$USER = $HOME ]]; then
    # warn if linux commands are hit
    alias ldd="echo ldd is not on OSX. use 'otool -L' instead."
    alias strace="echo strace is not on OSX. use dtruss"

    # require `brew install binutils coreutils findutils`
    path=(/usr/local/opt/coreutils/libexec/gnubin(N-/) $path)
    export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
    # findutils
    alias find=gfind
    alias xargs=gxargs

fi
